name: Deploy to Ubuntu Server

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          repository: sprintTZ/sprint-web-site
          ref: ${{ github.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}  # Use the default GitHub token for authentication

      # Your other steps here for updating project on VM and deploying to the server
      # - name: Update project on VM
      #   uses: appleboy/scp-action@master
      #   with:
      #     host: ${{ secrets.REMOTE_HOST }}
      #     username: ${{ secrets.SERVER_USER }}
      #     password: ${{ secrets.SERVER_PASSWORD }}
      #     port: ${{ secrets.SERVER_PORT }}
      #     source: .
      #     target: /home/sprintdevs/sprint-web-site

      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.10
        with:
          # username: ${{ secrets.SERVER_USER }}
          username: ${{ secrets.SERVER_USER }}
          # host: ${{ secrets.REMOTE_HOST }}
          # host: ${{ secrets.REMOTE_HOST }}
          host: ${{ secrets.REMOTE_HOST }}
          password: ${{ secrets.SERVER_PASSWORD }}
          # password: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            cd /home/sprintdevs/sprintTZ/sprint-web-site
            git pull origin develop
            # npm install
            # npm run build
            # /home/sprintdevs/sprintTZ/sprint-web-site
